apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dqn-profiles-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dqn-car-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dqn-car
  template:
    metadata:
      labels:
        app: dqn-car
    spec:
      containers:
      - name: dqn-car-container
        image: dqn-car-simulation:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http-ws
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - name: profiles-data
          mountPath: /app/profiles
      volumes:
      - name: profiles-data
        persistentVolumeClaim:
          claimName: dqn-profiles-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dqn-car-nodeport-service
spec:
  type: NodePort
  selector:
    app: dqn-car
  ports:
    - name: http-ws
      port: 8000
      targetPort: 8000
      nodePort: 30080
